#include <iostream>
#include <pcl/io/pcd_io.h>
#include <pcl/point_types.h>
#include <pcl/filters/extract_indices.h>
#include <pcl/filters/voxel_grid.h>
#include <pcl/features/normal_3d.h>
#include <pcl/segmentation/sac_segmentation.h>
#include <pcl/visualization/pcl_visualizer.h>
#include <pcl/point_cloud.h>
#include <pcl/octree/octree.h>
// 用于区域生长
#include <pcl/segmentation/region_growing.h>
// 用于搜索
#include <pcl/search/search.h>
// 用于滤波
#include <pcl/filters/statistical_outlier_removal.h>
#include <pcl/filters/passthrough.h>
